dribdat/__init__.py
"""Main application package."""

dribdat/admin/__init__.py
# -*- coding: utf-8 -*-

from . import views

dribdat/admin/views.py
# -*- coding: utf-8 -*-

from flask import (
    Blueprint, render_template, redirect, url_for,
    request, flash, jsonify
)
from flask_login import login_required

from ..utils import sanitize_input
from ..extensions import db, cache
from ..decorators import admin_required
from ..aggregation import GetProjectData, SyncProjectData
from ..user.models import Role, User, Event, Project, Category, Resource
from .forms import (
    RoleForm,
    UserForm, UserProfileForm,
    EventForm, ProjectForm,
    CategoryForm, ResourceForm,
)

from datetime import datetime
import random
import string

# from os import path


blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@login_required
@admin_required
def index():
    event = Event.query.filter_by(is_current=True).first()
    stats = [
        {
            'value': Event.query.count(),
            'text': 'Events',
            'icon': 'calendar',
            'height': 10
        }, {
            'value': User.query.count(),
            'text': 'Users',
            'icon': 'user',
            'height': 11
        }, {
            'value': Project.query.filter(Project.progress < 0).count(),
            'text': 'Challenges',
            'icon': 'trophy',
            'height': 13
        }, {
            'value': Project.query.filter(Project.progress >= 0).count(),
            'text': 'Projects',
            'icon': 'star',
            'height': 16
        },
    ]
    return render_template('admin/index.html',
                           stats=stats, default_event=event, active='index')


@blueprint.route('/users')
@blueprint.route('/users/pp/<int:page>')
@login_required
@admin_required
def users(page=1):
    sort_by = request.args.get('sort')
    if sort_by == 'id':
        users = User.query.order_by(
            User.id.asc()
        )
    elif sort_by == 'admin':
        users = User.query.order_by(
            User.is_admin.desc()
        )
    elif sort_by == 'sso':
        users = User.query.order_by(
            User.sso_id.asc()
        )
    elif sort_by == 'created':
        users = User.query.order_by(
            User.created_at.desc()
        )
    elif sort_by == 'email':
        users = User.query.order_by(
            User.email.asc()
        )
    elif sort_by == 'username':
        users = User.query.order_by(
            User.username.asc()
        )
    else:  # Default: updated
        users = User.query.order_by(
            User.updated_at.desc()
        )
    search_by = request.args.get('search')
    if search_by and len(search_by) > 1:
        q = "%%%s%%" % search_by.lower()
        users = users.filter(User.username.ilike(q))
    users = users.paginate(page, per_page=20)
    return render_template('admin/users.html',
                           data=users, endpoint='admin.users', active='users')


@blueprint.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))
    if form.validate_on_submit():
        originalhash = user.password
        del form.id
        user.username = sanitize_input(form.username.data)
        del form.username
        form.populate_obj(user)
        if form.password.data:
            user.set_password(form.password.data)
        else:
            user.password = originalhash
        user.updated_at = datetime.utcnow()
        db.session.add(user)
        db.session.commit()

        flash('User updated.', 'success')
        return users()

    return render_template('admin/useredit.html', user=user, form=form)


@blueprint.route('/user/<int:user_id>/profile', methods=['GET', 'POST'])
@login_required
@admin_required
def user_profile(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserProfileForm(obj=user, next=request.args.get('next'))
    form.roles.choices = [(r.id, r.name) for r in Role.query.order_by('name')]
    if form.validate_on_submit():
        del form.id
        # Assign roles
        user.roles = [Role.query.filter_by(
            id=r).first() for r in form.roles.data]
        del form.roles
        form.populate_obj(user)
        user.updated_at = datetime.utcnow()
        db.session.add(user)
        db.session.commit()

        flash('User updated.', 'success')
        return users()

    if not form.roles.choices:
        del form.roles
    else:
        form.roles.data = [(r.id) for r in user.roles]
    return render_template('admin/userprofile.html', user=user, form=form)


@blueprint.route('/user/new', methods=['GET', 'POST'])
@login_required
@admin_required
def user_new():
    user = User()
    user.active = True
    form = UserForm(obj=user, next=request.args.get('next'))
    del form.active
    if form.validate_on_submit():
        del form.id
        user.username = sanitize_input(form.username.data)
        del form.username
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()

        flash('User added.', 'success')
        return users()

    return render_template('admin/usernew.html', form=form)


@blueprint.route('/user/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def user_delete(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    if user.is_admin or user.active:
        flash('Admins and active users may not be deleted.', 'warning')
    elif len(user.projects) > 0:
        pl = ", ".join([str(i.name) for i in user.projects])
        flash('No users owning projects (%s) may be deleted.' % pl, 'warning')
    else:
        user.delete()
        flash('User deleted.', 'success')
    return users()


""" Get a reasonably secure password """


def get_random_alphanumeric_string(length=24):
    return ''.join(
        (random.SystemRandom().choice(string.ascii_letters + string.digits)
         for i in range(length)))


""" Retrieves a user by name """


def get_user_by_name(username):
    if not username:
        return None
    username = username.strip()
    if not username:
        return None
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('Username %s not found!' % username, 'warning')
        return None
    return user


@blueprint.route('/user/<int:user_id>/reset/')
@login_required
@admin_required
def user_reset(user_id):
    """Reset user password."""
    user = User.query.filter_by(id=user_id).first_or_404()
    newpw = get_random_alphanumeric_string()
    user.set_password(newpw)
    db.session.add(user)
    db.session.commit()
    return render_template('admin/reset.html', newpw=newpw, email=user.email)


@blueprint.route('/user/<int:user_id>/deactivate/')
@login_required
@admin_required
def user_deactivate(user_id, reactivate=False):
    """Manage activation of user account."""
    user = User.query.filter_by(id=user_id).first_or_404()
    user.active = reactivate
    db.session.add(user)
    db.session.commit()
    if reactivate:
        flash('User %s is now active.' % user.username, 'success')
    else:
        flash('User %s deactivated.' % user.username, 'warning')
    return users()


@blueprint.route('/user/<int:user_id>/reactivate/')
@login_required
@admin_required
def user_reactivate(user_id):
    """Reactivate user account."""
    return user_deactivate(user_id, True)

##############
##############
##############


@blueprint.route('/events')
@login_required
@admin_required
def events():
    events = Event.query.order_by(Event.starts_at.desc()).all()
    return render_template('admin/events.html', events=events, active='events')


@blueprint.route('/event/<int:event_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def event(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    form = EventForm(obj=event, next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(event)
        event.starts_at = datetime.combine(
            form.starts_date.data, form.starts_time.data)
        event.ends_at = datetime.combine(
            form.ends_date.data, form.ends_time.data)

        db.session.add(event)
        db.session.commit()

        cache.clear()

        flash('Event updated.', 'success')
        cache.clear()
        return redirect(url_for("admin.events"))

    form.starts_date.data = event.starts_at
    form.starts_time.data = event.starts_at
    form.ends_date.data = event.ends_at
    form.ends_time.data = event.ends_at
    return render_template('admin/event.html', event=event, form=form)


@blueprint.route('/event/<int:event_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def event_delete(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    if event.is_current:
        flash('Event must not be set as current to delete.', 'warning')
    elif len(event.categories) > 0:
        flash('No categories may be assigned to event to delete.', 'warning')
    elif len(event.projects) > 0:
        flash('No projects may be assigned to event to delete.', 'warning')
    else:
        event.delete()
        cache.clear()
        flash('Event deleted.', 'success')
    return events()


@blueprint.route('/event/<int:event_id>/autosync', methods=['GET', 'POST'])
@login_required
@admin_required
def event_autosync(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    count = 0
    for project in event.projects:
        if not project.is_autoupdateable:
            continue
        data = GetProjectData(project.autotext_url)
        if 'name' not in data:
            flash("Could not sync: %s" % project.name, 'warning')
            continue
        SyncProjectData(project, data)
        count += 1
    flash("%d projects synced." % count, 'success')
    return event_projects(event.id)


##############
##############
##############


@blueprint.route('/projects')

dribdat/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""

from flask import Flask, render_template
from flask_cors import CORS
from flask_misaka import Misaka
from flask_mailman import Mail
from flask_talisman import Talisman
from werkzeug.middleware.proxy_fix import ProxyFix
from micawber.providers import bootstrap_basic
from whitenoise import WhiteNoise
from pytz import timezone
from urllib.parse import quote_plus
from dribdat import commands, public, admin
from dribdat.assets import assets  # noqa: I005
from dribdat.sso import get_auth_blueprint
from dribdat.extensions import (
    hashing,
    cache,
    db,
    login_manager,
    migrate,
)
from dribdat.settings import ProdConfig  # noqa: I005
from dribdat.utils import timesince
from dribdat.onebox import make_oembedplus


def init_app(config_object=ProdConfig):
    """Define an application factory.

    See: http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)

    # Set up cross-site access to the API
    if app.config['SERVER_CORS']:
        CORS(app, resources={r"/api/*": {"origins": "*"}})
        app.config['CORS_HEADERS'] = 'Content-Type'

    # Set up using an external proxy/static server
    if app.config['SERVER_PROXY']:
        app.wsgi_app = ProxyFix(app, x_for=1, x_proto=1, x_host=1)
    else:
        # Internally optimize static file hosting
        app.wsgi_app = WhiteNoise(app.wsgi_app, prefix='static/')
        for static in ('css', 'img', 'js', 'public'):
            app.wsgi_app.add_files('dribdat/static/' + static)

    register_extensions(app)
    register_blueprints(app)
    register_oauthhandlers(app)
    register_errorhandlers(app)
    register_filters(app)
    register_loggers(app)
    register_shellcontext(app)
    register_commands(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    hashing.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    init_mailman(app)
    init_talisman(app)
    return None


def init_mailman(app):
    """Initialize mailer support."""
    if 'MAIL_SERVER' in app.config and app.config['MAIL_SERVER']:
        if not app.config['MAIL_DEFAULT_SENDER']:
            app.logger.warn('MAIL_DEFAULT_SENDER is required to send email')
        else:
            mail = Mail()
            mail.init_app(app)


def init_talisman(app):
    """Initialize Talisman support."""
    if 'SERVER_SSL' in app.config and app.config['SERVER_SSL']:
        Talisman(app,
                 content_security_policy=app.config['CSP_DIRECTIVES'],
                 frame_options_allow_from='*')


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(public.project.blueprint)
    app.register_blueprint(public.auth.blueprint)
    app.register_blueprint(public.api.blueprint)
    app.register_blueprint(admin.views.blueprint)
    return None


def register_oauthhandlers(app):
    """Set up OAuth handlers based on configuration."""
    blueprint = get_auth_blueprint(app)
    if blueprint is not None:
        app.register_blueprint(blueprint, url_prefix="/oauth")


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""
    def shell_context():
        """Shell context objects."""
        from dribdat.user.models import User
        return {
            'db': db,
            'User': User}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.lint)
    app.cli.add_command(commands.clean)
    app.cli.add_command(commands.urls)


def register_filters(app):
    """Register filters for templates."""
    #
    # Conversion of Markdown to HTML
    Misaka(app, autolink=True, fenced_code=True,
           strikethrough=True, tables=True)

    # Registration of handlers for micawber
    app.oembed_providers = bootstrap_basic()

    @app.template_filter()
    def onebox(value):
        return make_oembedplus(
            value, app.oembed_providers, maxwidth=600, maxheight=400
        )

    # Timezone helper
    app.tz = timezone(app.config['TIME_ZONE'])

    # Lambda filters for safe image_url's
    app.jinja_env.filters['quote_plus'] = lambda u: quote_plus(u, ':/?&=')

    # Custom filters
    @app.template_filter()
    def since_date(value):
        return timesince(value)

    @app.template_filter()
    def until_date(value):
        return timesince(value, default="now!", until=True)

    @app.template_filter()
    def format_date(value, format='%d.%m.%Y'):
        return value.strftime(format)

    @app.template_filter()
    def format_datetime(value, format='%d.%m.%Y %H:%M'):
        return value.strftime(format)


def register_loggers(app):
    """Initialize and configure logging."""
    import logging
    stream_handler = logging.StreamHandler()
    app.logger.addHandler(stream_handler)
    app.logger.setLevel(logging.INFO)

dribdat/boxout/__init__.py
# -*- coding: utf-8 -*-
"""Boxout modules for parsing resource types."""

dribdat/sso/__init__.py
"""Single Sign-On extensions."""

from .ssoutils import get_auth_blueprint

dribdat/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import validators  # noqa

from .constants import (
    USER_ROLE, ADMIN, USER, USER_STATUS, ACTIVE,
    isUserActive,
    getProjectStages,
    validateProjectData,
    resourceTypeList,
    projectProgressList,
)

dribdat/templates/includes/analytics.html
{% if config.ANALYTICS_FATHOM %}
<!-- Fathom - beautiful, simple website analytics -->
    {% if config.ANALYTICS_FATHOM_SITE %}
    <script src="https://{{ config.ANALYTICS_FATHOM_SITE }}/script.js" site="{{ config.ANALYTICS_FATHOM }}" async defer></script>
    {% else %}
    <script src="https://cdn.usefathom.com/script.js" site="{{ config.ANALYTICS_FATHOM }}" async defer></script>
    {% endif %}
<!-- / Fathom -->
{% endif %}

{% if config.ANALYTICS_SIMPLE %}
<!-- Simple Analytics - Simple, clean, privacy-friendly analytics -->
<script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
<noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt=""
/></noscript>
{% endif %}

{% if config.ANALYTICS_GOOGLE %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ config.ANALYTICS_GOOGLE }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '{{ config.ANALYTICS_GOOGLE }}');
</script>
<!-- / Google Analytics -->
{% endif %}

dribdat/templates/includes/eventhome.html
<div class="event-header">
  <a href="{{ url_for('public.event', event_id=event.id) }}">
    {% if event.logo_url and not event.gallery_url %}
      <div class="section-header-logo">
        <img id="event-logo" src="{{ event.logo_url }}" alt="Logo" title="{{ event.hostname }}">
      </div>
    {% endif %}
    <div class="section-header-content">
      <h3 class="event-name">{{ event.name }}</h3>
      {% if not event.lock_resources %}
        <span class="event-date">
          <i class="fa fa-calendar"></i>
          {{ event.date }}</span>
      {% endif %}
      {% if event.hostname %}
        <span class="event-hostname ml-2">
          <i class="fa fa-bank"></i>
          {{ event.hostname }}</span>
      {% endif %}
      {% if event.location %}
        <span class="event-location ml-2">
          <i class="fa fa-map"></i>
          {{ event.location }}</span>
      {% endif %}
    </div>
  </a>
  
  {% if event.summary %}
    <div class="home-description">
      {% if event.summary|trim %}
        <p>{{ event.summary }}</p>
      {% endif %}
    </div>
  {% elif event.description %}
    <div class="home-description">
      {{ event.description|markdown }}
    </div>
  {% endif %}

  <div class="home-nav">
    <div class="embed-view">
      {{ render_embed_event(event, event.projects, False) }}
    </div>
    <div class="home-buttons" aria-label="Main navigation">
      <a href="{{ url_for('public.event', event_id=event.id) }}"
         class="btn btn-lg btn-warning p-3">
        {% if event.has_finished %}
          <i class="fa fa-certificate" aria-hidden="true"></i>
          All Results
        {% elif event.has_started %}
          <i class="fa fa-rocket" aria-hidden="true"></i>
          All Projects
        {% else %}
          <!-- Event not yet started -->
          <i class="fa fa-lightbulb-o" aria-hidden="true"></i>
          All Challenges
        {% endif %}
      </a>
    </div>
  </div>

</div><!-- /.event-header -->

dribdat/templates/includes/footer.html
<footer>
  <a class="dribdat-logo" href="{{ url_for('public.home') }}">
    <img src="{{ url_for('static', filename='img/logo11.png') }}">
  </a>
  <ul class="footer-nav">
    {% if current_user and current_user.is_authenticated %}
      {% if current_user.is_admin %}
        <li>
          <a href="{{ url_for('admin.index') }}">
            <i class="fa fa-gear" aria-hidden="true"></i>
            Admin
          </a>
        </li>
      {% endif %}
      <li>
        <a href="{{ url_for('public.user', username=current_user.username) }}" title="{{ current_user.username }}">
          <i class="fa fa-key" aria-hidden="true"></i>
          My Profile
        </a>
      </li>
      <li>
        <a href="{{ url_for('auth.logout') }}">
          <i class="fa fa-sign-out" aria-hidden="true"></i>
          Logout
        </a>
      </li>
    {% else %}
      <li>
        <a href="{{ url_for('auth.login') }}">
          <i class="fa fa-sign-in" aria-hidden="true"></i>
          Login
        </a>
      </li>
    {% endif %}
    {% if config.ANALYTICS_HREF %}
    <li>
      <a href="{{ config.ANALYTICS_HREF }}">&#128200;&nbsp;Analytics</a>
    </li>
    {% endif %}

    <li>
      <a href="{{ url_for('public.about') }}">&#128214;&nbsp;About</a>
    </li>

    <li>
      <a class="darkmode" href="#">&#127763;&nbsp;<span>Dark</span></a>
    </li>
  </ul>
</footer>

dribdat/templates/includes/header.html
<div class="container event-header">
  <div class="section section-centered section-header">
    {% if event.logo_url %}
      <div class="section-header-logo">
        <a href="{{ url_for('public.event', event_id=event.id) }}">
          <img id="event-logo" src="{{ event.logo_url }}" alt="Logo" title="{{ event.hostname }}">
        </a>
      </div>
    {% endif %}
    <div class="section-header-content">
      <a href="{{ url_for('public.event', event_id=event.id) }}">
        <h3 class="event-name">{{ event.name }}</h3>
      </a>
      {% if event.hostname %}
        <div class="event-hostname">
          <i class="fa fa-bank"></i>
          {{ event.hostname }}</div>
      {% endif %}
      {% if not event.lock_resources %}
        <div class="event-date">
          <i class="fa fa-calendar"></i>
          {{ event.date }}</div>
      {% endif %}
      {% if event.location %}
        <div class="event-location">
          <i class="fa fa-map"></i>
          {{ event.location }}</div>
      {% endif %}
    </div>
  </div>
</div>

dribdat/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-faded" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}" title="Home page">
      <i style="-moz-transform: scale(1, 1); -webkit-transform: scale(1, 1); -o-transform: scale(1, 1); -ms-transform: scale(1, 1); transform: scale(1, 1);" class="fa fa-thumbs-up" aria-hidden="true"></i>
      <i style="-moz-transform: scale(1, 1); -webkit-transform: scale(1, 1); -o-transform: scale(1, 1); -ms-transform: scale(1, 1); transform: scale(1, 1);" class="fa fa-lightbulb-o" aria-hidden="true"></i>
      <i style="-moz-transform: scale(-1, 1); -webkit-transform: scale(-1, 1); -o-transform: scale(-1, 1); -ms-transform: scale(-1, 1); transform: scale(-1, 1);" class="fa fa-thumbs-up" aria-hidden="true"></i>
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-main-collapse">
    <ul class="navbar-nav navbar-left mr-auto nav-fill">

      {% if tabs %}
        {% for tab, link in tabs %}
        <li class="nav-item">
          <a class="nav-link {% if active == tab %}active{% endif %}" href="{{ link }}">{{ tab|capitalize }}</a>
        </li>
        {% endfor %}
      {% endif %}

      <li class="nav-item">
        <a class="nav-link {% if active == 'dribs' %}active{% endif %}" href="{{ url_for('public.dribs') }}">
          <i class="fa fa-comment" aria-hidden="true"></i>
          Dribs
        </a>
      </li>
      {% if event and not event.lock_resources %}
        <li class="nav-item">
          <a class="nav-link {% if active == 'projects' %}active{% endif %}" href="{{ url_for('public.event', event_id=event.id) }}#top">
            <i class="fa fa-star" aria-hidden="true"></i>
            {% if event.has_finished %}
              Results
            {% elif event.has_started %}
              Projects
            {% else %}
              Challenges
            {% endif %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active == 'participants' %}active{% endif %}" href="{{ url_for('public.event_participants', event_id=event.id) }}">
            <i class="fa fa-child" aria-hidden="true"></i>
            People
          </a>
        </li>
      {% endif %}

      {% if current_user and current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link{{ ' active' if active == 'profile' }}" href="{{ url_for('public.user', username=current_user.username) }}" title="{{ current_user.username }}">
              <i class="fa fa-key" aria-hidden="true"></i>
              Profile
            </a>
          </li>
          {% if current_user.is_admin %}
            <li class="nav-item admin-area">
              <a class="nav-link{{ ' active' if active == 'index' }}" href="{{ url_for('admin.index') }}">
                <i class="fa fa-gear" aria-hidden="true"></i>
                Admin
              </a>
            </li>
            {% if event %}
              <li class="nav-item">
                <a href="{{ url_for('public.event_print', event_id=event.id) }}"
                   title="Detailed overview of this event" class="nav-link">
                  <i class="fa fa-print" aria-hidden="true"></i>
                  Report</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('admin.event', event_id=event.id) }}"
                   title="Edit event details" class="nav-link">
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                  Edit</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('admin.project_new', event_id=event.id) }}"
                   title="Add a project here" class="nav-link">
                  <i class="fa fa-plus"></i>
                  Add</a>
              </li>
            {% endif %}
          {% endif %}
      {% else %}
        <li class="nav-item">
          <a class="nav-link nav-login" href="{{ url_for('auth.login') }}">
            <i class="fa fa-sign-in" aria-hidden="true"></i>
            Login
          </a>
        </li>
      {% endif %}

      <form class="form-inline nav-item" action="{{ url_for('public.about') }}" method="get">
        <button class="btn my-2 my-sm-0 {% if active != 'about' %}text-secondary{% endif %}" type="submit">
          <i class="fa fa-search" aria-hidden="true"></i>
        </button>
        <!-- <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="Search" name="q" size=7> -->
      </form>

    </ul>



  </div><!-- /.navbar-collapse -->

</nav>

dribdat/templates/includes/pagination.html
<!-- Pagination widget -->
{% if data.pages > 1 %}
<div class="nav-pagination">
	{% if data.has_prev %}
		<a href="{{ url_for(endpoint, page=data.prev_num) }}" class="btn btn-secondary">&#9664;&nbsp; Previous</a>
	{% endif %}
	<span class="pagination m-3" style="display:inline-block">
	{%- for page in data.iter_pages() %}
		{% if page %}
			{% if page != data.page %}
				<a href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
			{% else %}
				<strong>{{ page }}</strong>
			{% endif %}
		{% else %}
			<span class="ellipsis">…</span>
		{% endif %}
	{%- endfor %}
	</span>
	{% if data.has_next %}
		<a href="{{ url_for(endpoint, page=data.next_num) }}" class="btn btn-secondary">Next &nbsp;&#9654;</a>
	{% endif %}
</div>
{% endif %}

dribdat/templates/includes/search.html
<!-- Search box widget -->
<form action="{{ url_for(endpoint) }}" class="admin-search row g-3">
	<div class="col-auto ml-2 pr-0">
		<input class="form-control" placeholder="Search ..." name="search">
	</div><div class="col-auto">
		<input class="btn btn-light" type="submit" value="Go">
	</div>
</form>